---
title: "R Notebook"
output: html_notebook
---

```{r}
library(MASS)
library(tidyverse)
library(skimr)
```
##Problem 7.2

https://www.tidymodels.org/learn/statistics/bootstrap/

```{r}
posterior <- read_csv("../data/posterior_gdpInfantMortality.csv") %>% 
  rename(country = X1) %>% 
  janitor::clean_names() %>% 
  filter(!is.na(gdp) & !is.na(infant_mortality)) %>% 
  mutate(across(where(is_numeric), log, .names = "{.col}_log"))
```



```{r}
# nlsfit <- nls(mpg ~ k / wt + b, mtcars, start = list(k = 1, b = 0))
library(tidymodels)

nlsfit <- nls(infant_mortality_log ~ a + (b * gdp_log),
              posterior,
              start = list(a = 1, b = 0)
              )

summary(nlsfit)

ggplot(posterior,
       aes(gdp_log, infant_mortality_log)) +
  geom_point() +
  geom_line(aes(y = predict(nlsfit)))
```
```{r}
tidy_nls_fit <- tidy(nlsfit)
tidy_nls_fit
```
```{r}

# extract coefficients from tidied model output
a_hat <- tidy_nls_fit[[which(tidy_nls_fit$term == "a"), "estimate"]]
a_se <- tidy_nls_fit[[which(tidy_nls_fit$term == "a"), "std.error"]]

b_hat <- tidy_nls_fit[[which(tidy_nls_fit$term == "b"), "estimate"]]
b_se <- tidy_nls_fit[[which(tidy_nls_fit$term == "b"), "std.error"]]

# calculate 80% confidence intervals for model coefficients a
a_ci_80 <- a_hat + (qt(p = c(0.1, 0.9), df = length(posterior) - 2) * a_se)
a_ci_80


# calculate 80% confidence intervals for model coefficent b
b_ci_80 <- b_hat + (qt(p = c(0.1, 0.9), df = length(posterior) - 2) * b_se)
b_ci_80


```

7.2.4

```{r}
posterior_coeff <- read_csv("../data/posterior_posteriorsGdpInfantMortality.csv")

coeffs <- names(posterior_coeff)
coeffs <- set_names(coeffs)

coeffs

posterior_coeff_histogram <- function(x) {
  
  p <- ggplot(data = posterior_coeff,
              mapping = aes(x = .data[[x]]))
  
  p + geom_histogram()
}

plots <- map(coeffs,  ~ posterior_coeff_histogram(.x))

plots

```

```{r}
posterior_coeff %>% 
  map(~ quantile(.x, c(0.1, 0.9)))
```

7.2.6 Correlations
```{r}
correlation_plot <- function(x, y){
  
  p <- ggplot(data = posterior_coeff,
              mapping = aes(x = .data[[x]],
                            y = .data[[y]]
                            )
              )
  
  p + geom_point()
}
  

map(coeffs, ~ correlation_plot("alpha", .x))
map(coeffs, ~ correlation_plot("beta", .x))
map(coeffs, ~ correlation_plot("sigma", .x))


```
7.2.7

```{r}

dat <- posterior
dat

# create a dataframe of samples from the priors of the model parameters
parameter_priors <- tibble(alpha = rnorm(n = 10000, mean = 0, sd = 10),
                           beta = rnorm(n = 10000, mean = 0, sd = 10),
                           sigma = abs(rnorm(n = 10000, mean = 0, sd = 5))
                            )

sample_from_prior_predictive <- function(){
  
  # sample at random a set of parameters (ai, bi, si) from the prior distributions
  rand_parameter_priors <- parameter_priors %>% 
    sample_n(1)
  
  a <- rand_parameter_priors[[1]]
  b <- rand_parameter_priors[[2]]
  s <- rand_parameter_priors[[3]]
  
  
  # sample at random gdp value from the dataset 
  random_country <- dat %>% 
    sample_n(1)
  
  gdp <- random_country[[1, 'gdp']]
  
  # predict infant mortality rate for the sampled country using the sampled parameters (ai, bi, si) 
  
  mu <- a + (b * log(gdp))
  
  predicted_infant_mortality_rate_log <- rnorm(n = 1, mean = mu, sd = s)
  predicted_infant_mortality_rate_log
}

# Generate prior predictive distribution
num_sims <- 10000
prior_pred <- tibble(sim_num = 0:num_sims,
                     prior_pred = map_dbl(sim_num, ~sample_from_prior_predictive()))

# Compare prior predictive distribution with the data that has been collected
prior_pred %>% 
  skim(prior_pred)

dat %>% 
  skim(infant_mortality_log)
```
Problem 7.2.8. Generate samples from the posterior predictive
```{r}

sample_var_from_df <-  function(df, variable_name){
  
  df %>% 
    sample_n(1) %>% 
    select({{variable_name}}) %>%
    as.double()
}

infant_mortality_model <-  function(a, b, s, gdp){
    
  mu <- a + (b * log(gdp))

  predicted_infant_mortality_rate_log <- rnorm(n = 1, mean = mu, sd = s)
  predicted_infant_mortality_rate_log
}


sample_from_posterier_prediction <- function(){
  
  # sample (ai, bi, si) from posterior parameter distribution
  a <- sample_var_from_df(posterior_coeff, alpha)
  b <- sample_var_from_df(posterior_coeff, beta)
  s <- sample_var_from_df(posterior_coeff, sigma)
  
  # sample a gdp at random
  gdp <- sample_var_from_df(dat, gdp)
  
  # calculate predicted infant mortality rate from gdp and ai, bi, si
  infant_mortality_model(a, b, s, gdp)
}

# simulate posterior predictive distribution
num_sims <- 10000
post_pred <- tibble(sim_num = 0:num_sims,
                     log_infant_mortality = map_dbl(sim_num, ~ sample_from_posterier_prediction()))

post_pred %>% 
  skim(log_infant_mortality)

```


